apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actor-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: global-redis-db-service.default.svc.cluster.local:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
