apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: session-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: session-db-service.default.svc.cluster.local:6379
  - name: redisPassword
    value: ""
scopes:
- session-api